### ISSUE TITLE
Calibrate speed block is confusing

### ISSUE THREAD

**Issue by KitronikLtd** [KitronikLtd/pxt-kitronik-servo-lite#10]
The wording of the blocks and the comments seem to indicate an actual change in speed, whereas speed is constant and the distance travelled changes. It needs to be clear to the user that speed will not vary, and that increasing the mm/s or deg/s will actually reduce the distance travelled in the same length of time.

**Comment by chewi** [comment]
Yes, I was confused by this as well.
