### ISSUE TITLE
Validate the use of division operator in this package for MakeCode update

### ISSUE THREAD

**Issue by abchatra** [KitronikLtd/pxt-kitronik-servo-lite#11]
MakeCode for the micro:bit update is coming soon. Part of the update is floating point support. Existing MakeCode website supports only integer division which means
1/2 = 0
With this update 1/2 = 0.5

__Action for you:__
We have automatically detected this package uses division operator. Please take one of the following actions
- If the change to floating point division doesn't matter you can ignore and close this issue.
- If you want integer division then update your package typescript code to use integer division. Change  _a/b_ to  _Math.idiv(a, b)_

You can test your package on the update here: https://makecode.microbit.org/beta

All the details on the update: https://makecode.com/blog/microbit/v1-beta

div found in servolite.ts

**Comment by chewi** [comment]
I think this can be closed. We need the float accuracy.
