### ISSUE TITLE
Remove package from README

### ISSUE THREAD

**Issue by kimprice** [KitronikLtd/pxt-kitronik-servo-lite#18]
Please remove the following from the README as it is causing duplicate package imports:
\```package
pxt-kitronik-servo-lite=github:KitronikLtd/pxt-kitronik-servo-lite
\```

See https://github.com/microsoft/pxt-microbit/issues/4832 for more info.

**Comment by JackAtKitronik** [comment]
Thanks. It's been removed [here](https://github.com/KitronikLtd/pxt-kitronik-servo-lite/commit/3d55278a7f745e09f8ffb8075453267a828a2bc2).
