### ISSUE TITLE
Link to rendered docs

### ISSUE THREAD

**Issue by pelikhan** [KitronikLtd/pxt-kitronik-servo-lite#2]
... is https://pxt.microbit.org/pkg/KitronikLtd/pxt-kitronik-servo-lite .

**Comment by DaveAtKitronik** [comment]
@pelikhan what does this mean? Not sure what to fix...

**Comment by pelikhan** [comment]
You add it as the web site for this repo. Note that you need to request the package to be approved to the micro:bit foundation -- unless your users will see this:
![image](https://cloud.githubusercontent.com/assets/4175913/26814194/6a0a5e1c-4a38-11e7-8eba-178ec9decafd.png)
