### ISSUE TITLE
what is the status of this repo?

### ISSUE THREAD

**Issue by pelikhan** [KitronikLtd/pxt-kitronik-servo-lite#3]
Is it ready to be surfaced in the editor? @DaveAtKitronik

**Comment by DaveAtKitronik** [comment]
@pelikhan The code is stable and can be used. We have a list internally of additional blocks we will add as time and resource permits. The only outstanding thing I'd like to do before its officially live is to get the PXT editor icon to be 'Kit' - our micro:bit Robot icon. 
![kit robot logo - green for pxt editor](https://user-images.githubusercontent.com/25896029/27122121-a64973b8-50e1-11e7-916f-710ccb8e3228.png)
I couldn't figure out how to do that previously.

**Comment by pelikhan** [comment]
Custom icons for packages is not supported yet.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DaveAtKitronik** [comment]
@pelikhan  In that case I think that its ready, unless the rendered docs issue has something to be done to make it work?

**Comment by pelikhan** [comment]
I'll enable it and we push a PR to fix any issues.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DaveAtKitronik** [comment]
Excellent.
